image: python:3.8

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
    - pip3 install virtualenv --upgrade
    - mkdir folder
    - cd folder
    - python -m virtualenv venv
    - source venv/bin/activate
    - pip3 install numpy
    - pip3 install pandas
    - deactivate
    - dir
    - cd ..
  script:
    - sam package --output-template-file packaged.yaml --s3-bucket johnrteixeira-movie-recommendation-engine
    - sam deploy --template-file packaged.yaml --stack-name movie-recommendation-engine --s3-bucket johnrteixeira-movie-recommendation-engine --capabilities CAPABILITY_IAM --region ca-central-1
  environment: production