image: python:3.8

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
    - pip3 install virtualenv --upgrade
    - mkdir folder
    - cd folder
    - python -m virtualenv venv
    - source venv/bin/activate
    - pip3 install numpy
    - pip3 install pandas
    - deactivate
    - dir
    - cd vvenv/lib64/python3.8/site-packages/*
    - cd ..
    - zip -r library_layer.zip python
    - aws lambda publish-layer-version --layer-name library-layer --zip-file fileb://library_layer.zip --compatible-runtimes python3.8
  script:
    - sam package --output-template-file packaged.yaml --s3-bucket johnrteixeira-movie-recommendation-engine
    - sam deploy --template-file packaged.yaml --stack-name movie-recommendation-engine --s3-bucket johnrteixeira-movie-recommendation-engine --capabilities CAPABILITY_IAM --region ca-central-1
  environment: production